### PR TITLE
CDRIVER-2083 use target_compile_definitions

### PR DESCRIPTION
**Pull request by xdg**
add_definitions() has global effect, so isn't good to include
in a .cmake file.  This commit instead publishes the definitions in a
variable and lets consumers set it on a target the same way they set
library/include paths.

libmongoc will need a corresponding update.

### CODE REVIEW

**Comment by ajdavis** [comment]
Let's make the same change to examples/cmake/find_package/CMakeLists.txt:
```
target_compile_definitions (hello_bson PRIVATE ${BSON_DEFINITIONS})
```
It will have no effect; so let's prove that it has no effect by testing it. And someday, perhaps libbson-1.0-config.cmake *will* add to BSON_DEFINITIONS, the way libbson-static-1.0-config.cmake does now. We can encourage people to write forward-compatible CMake files in these examples.

**Comment by xdg** [comment]
In mongocxx, we're trying to move away from requiring users to make global changes as `link_directories()` does.  The second patch makes libbson provide libraries with absolute paths, which the CMake docs imply is idiomatic.

I'm sure there's a more straightforward way to do this, but we haven't found it yet and this way is expedient.  I'll have a similar patch for libmongoc soon.

(cc @jrassi)

**Comment by xdg** [comment]
Looks like I should rebase and test on windows as well.

**Comment by xdg** [comment]
Rebased and Evergreen patch build passes on Unix and Windows.  Does not include changes in this morning's [code review](https://mongodbcr.appspot.com/123910004/).

**Comment by ajdavis** [comment]
Rebased and merged, thanks!

**Pull request closed without merging**
