### PR TITLE
Build fixes for MSVC.

### PR DESCRIPTION
**Pull request by xpol**
1. Disable UTF-8 related test for MSVC, it just don't support UTF-8.
2. VS 2015 has snprintf()
3. VS 2015 removed _set_output_format()
4. VS 2015 defines timespec.

### CODE REVIEW

**Comment by bjori** [comment]
How is the UTF-8 tests failing?

That seems like a major issue if you can insert a key with UTF-8, but cannot read it back.

What does 'str' contain in the tests/test-json.c test for example?

**Comment by xpol** [comment]
visual can't compile strings literal contains non-ascii.

**Comment by xpol** [comment]
I should say "Disable tests that contains non ascii string literals, visual studio can't process them."

**Comment by ajdavis** [comment]
Thanks for the contribution, we're going to merge the _set_output_format and timespec fixes (with some modifications).

I don't understand why you need to ifdef-out the UTF-8 tests, however. With our VS2015 build system we can compile and run those tests in test-bson.c and test-json.c. Can you show us the error message? What precise version of Windows and Visual Studio are your running, please?

**Comment by ajdavis** [comment]
Merged in 4fb312c8650040dc7f6b3d4a3186c43d24e836e6.

**Comment by xpol** [comment]
Sorry, I have no Windows PC now.
As I know, at least in code page CP936 env, utf8 string literal will cause compiler error.

**Comment by ajdavis** [comment]
OK we'll replace the UTF-8 symbols with escape sequences: https://jira.mongodb.org/browse/CDRIVER-1003

**Comment by ajdavis** [comment]
The UTF-8 issue is fixed in https://github.com/mongodb/libbson/commit/d4feba4893bba4f41163b675cac40028eb72d7bc.

**Comment by xpol** [comment]
:+1:

**Pull request closed without merging**
