### PR TITLE
Fix Debian bug #832747

### PR DESCRIPTION
**Pull request by ajdavis**

### CODE REVIEW

**Comment by ajdavis** [comment]
@rcsanchez97 could you check my work?

**Comment by ajdavis** [comment]
Question about this patch: does this require libatomic to be available, and must we add its package to our requirements?

**Comment by rcsanchez97** [comment]
@ajdavis The patch looks fine.  The only question I have is if you mean
to carry this as a Debian-specific change (i.e., in the patch stack for
when the Debian package gets built) or if you intend to apply it
upstream eventually?

As far as the dependency goes, that is not necessary.  The libatomic
package is part of the gcc source package.  Since gcc is installed at
build time, the necessary runtime and development packages are there and
so it will compile without any additional build-time dependencies.  Were
this not the case, the package would fail to build because the necessary
headers and libraries would be missing.

When the package gets created its runtime dependencies are calculated
and the dependency on the libatomic runtime library gets handled
automatically:

 Depends: libatomic1 (>= 4.8), libc6 (>= 2.17), libyajl2 (>= 2.0.4)

**Comment by ajdavis** [comment]
Thanks Roberto. We're going to investigate whether to apply the patch upstream, but we'll need to support non-gcc compilers there:

https://jira.mongodb.org/browse/CDRIVER-1468

**Comment by rcsanchez97** [comment]
OK.  That makes sense.  Thanks for the info.

**Pull request merged**
