### PR TITLE
Added two functions bson_iter_as_double and bson_iter_as_int32.

### PR DESCRIPTION
**Pull request by GaelMagnan**
Also added the tests.

Those two functions would be nice in case we have mixed data type, and would complete the suite with bson_iter_as_int64 and bson_iter_as_bool.

### CODE REVIEW

**Comment by bjori** [comment]
I'm a little uncomfortable with as_int32() as it doesn't deal with int64 and you may not be consistently getting int32 as type int32. Its perfectly legal, and not that uncommon, to store int32 as bson int64 type.

**Comment by GaelMagnan** [comment]
I thought about that, the thing is I could do the same with int64, but what to do when the value cannot be contained in a int32? 

If you have any thoughts about how to handle that case I'll gladly do it. 

By the way, I was also looking into doing a as_utf8 function that would transform the value to it's utf8 representation, but I gave up. If somone wants to have a go at it...

**Comment by GaelMagnan** [comment]
@bjori I've added the int64 to int32 conversion.

**Comment by GaelMagnan** [comment]
Should I close this pr or do you want me to change something?

**Comment by bjori** [comment]
Sorry for the slow turnaround on this.

We aren't comfortable with the _as_int32 function, but the bson_iter_as_double is reasonable and good idea.

Do you mind rebase the _as_int32 out and file an new feature ticket at https://jira.mongodb.org/browse/CDRIVER

We should be able to merge this into 1.7.0

**Comment by GaelMagnan** [comment]
Done and done: https://jira.mongodb.org/browse/CDRIVER-2143

**Comment by bjori** [comment]
I think you may have forgotten to push the as_int32 removal?

**Comment by GaelMagnan** [comment]
You are right, sorry about that, it should be better now.

**Comment by bjori** [comment]
Merged as https://github.com/mongodb/libbson/commit/90ce96d7f5611f796bc9c2982d5225f27169a01a

Thanks!

**Pull request closed without merging**
