### PR TITLE
CDRIVER-613 remove GCC-specific min/max macros.

### PR DESCRIPTION
**Pull request by ajdavis**
CDRIVER-613 remove GCC-specific min/max macros.

### CODE REVIEW

**Comment by ajdavis** [comment]
https://jira.mongodb.org/browse/CDRIVER-613

**Comment by chergert** [comment]
I don't understand the motivation behind this.

**Comment by chergert** [comment]
If we *really* need ISO C compliance on GCC (I'm skeptical), perhaps just add an additional check for `__STRICT_ANSI__`.

**Comment by ajdavis** [comment]
Hi Christian! The motivation is, we might use BSON_MIN or BSON_MAX with
expressions that have side effects, and not see the resulting bugs until we
test on non-GCC platforms. Better for the macros to behave the same
everywhere, so we use them with proper caution.

On Fri, Apr 17, 2015 at 2:42 PM, Christian Hergert <notifications@github.com

**Comment by chergert** [comment]
Generally speaking, don't do that :)

The value of GCC-statement-expressions is two fold. 1) type checking that you are using the same types on both sides. 2) performance by hoisting function calls that are essentially pure (but not marked as such to the compiler) from being called multiple times. (like strlen, for example).

Doing side-effects in a MIN()/MAX() is almost never a good idea.

**Comment by acmorrow** [comment]
Overall, yes: we need to be able to compile our public headers without GNU extensions on GCC.

The problem isn't that we want people to use side effects in macros. The point is that they could do so and it would work correctly when using GCC, because the macro would mask the bug, and then not work correctly when they ported it elsewhere, and probably leave them very puzzled as to why.

Your point about the type checking is reasonable. I'd be OK with adding __STRICT_ANSI___ or similar though.

**Comment by chergert** [comment]
> Overall, yes: we need to be able to compile our public headers without GNU extensions on GCC.

I honestly don't see the value in this.

**Comment by acmorrow** [comment]
Because it allows the libbson headers to be used in contexts where GNU extensions are disallowed. We can't as library developers mandate their use. Please see https://jira.mongodb.org/browse/CDRIVER-613.

**Comment by chergert** [comment]
Maybe add a macro similar to BSON_GNUC_CHECK() such as BSON_GNUC_HAS_STMTEXPR() that checks for strict?

**Comment by ajdavis** [comment]
OK, I've gone with The Simplest Thing That Could Possibly Work, thanks guys.

**Pull request merged**
