### PR TITLE
CDRIVER-1374: Accept uppercase hex characters in bson_oid_is_valid()

### PR DESCRIPTION
**Pull request by jmikola**
https://jira.mongodb.org/browse/CDRIVER-1374

### CODE REVIEW

**Comment by bjori** [comment]
Thanks!

**Comment by bjori** [comment]
This PR broke our build :(
https://evergreen.mongodb.com/version/libbson_e76a3598b9c3d7403e61cf53f71f496bfc7d929e

```
 [2016/07/12 16:10:29.967] tests/test-oid.c: In function ‘test_bson_oid_init_from_string’:
 [2016/07/12 16:10:29.967] tests/test-oid.c:110:7: error: implicit declaration of function ‘strcasecmp’ [-Werror=implicit-function-declaration]
 [2016/07/12 16:10:29.967]        assert (!strcasecmp (str, gTestOidsCase[i]));
 [2016/07/12 16:10:29.967]        ^
```

**Comment by chergert** [comment]
We didn't abstract this into `bson_ascii_strcasecmp()` originally because we only had one use of it. It might make sense to do so now. (Just keep in mind it's not doing utf8 casefolding, so it's ascii only).

**Comment by bjori** [comment]
mongoc has a "workaround" for it: https://github.com/mongodb/mongo-c-driver/blob/master/src/mongoc/mongoc-util-private.h#L26

Makes sense to create `bson_ascii_str[n]casecmp`. I've added a ticket for it: https://jira.mongodb.org/browse/CDRIVER-1386

**Pull request merged**
