### PR TITLE
Removed string(CONCAT) as it not supported by all cmake versions.

### PR DESCRIPTION
**Pull request by arbishop**
* cmake_minimum_required(VERSION 2.8) is specified
* Ubuntu LTS is shipping with 2.8.12

### CODE REVIEW

**Comment by bjori** [comment]
Cross linking with https://jira.mongodb.org/browse/CDRIVER-1055

**Comment by ajdavis** [comment]
Thanks for all your contributions! We'll look at this PR and the Jira issue next month.

**Comment by arbishop** [comment]
No problem.  There are probably other solutions here, I do not care which path is taken.  Just want to point out that this is a blocker for updating, in my case, to 1.3.0.

I'd like to update, for the free bug fixes :)

**Comment by ajdavis** [comment]
Thanks! Fixed in libmongoc too:

https://github.com/mongodb/mongo-c-driver/commit/63d6fc1b914fbc03d4233278aaea3704e3521cd7

**Pull request merged**
