### PR TITLE
Clean up for 1.3.5-1 upload

### PR DESCRIPTION
**Pull request by rcsanchez97**
These are the changes to clean up for the 1.3.5-1 upload.

### CODE REVIEW

**Comment by acmorrow** [comment]
@rcsanchez97 As this is a patch level bump, is there any way to exhort the Ubuntu maintainers to bump the libbson and libmongoc versions in 16.04? They are currently at 1.3.1, which is pretty old. I don't know enough about the Ubuntu policy on taking patch versions into an LTS to know what their position would be.

**Comment by rcsanchez97** [comment]
A version bump in an LTS release seems unlikely unless the new package
corrects some security flaw or a high severity bug.  However, there are
two additional possibilities, either requesting that the new package be
accepted into trusty-updates or into trusty-backports.  I am not sure
what the process is for either of those.  You can look into it or, if
you prefer, I can look into it.

**Comment by acmorrow** [comment]
@rcsanchez97 It seem a little strange to me that an LTS wouldn't take bugfixe level changes in a library. It is a patch level bump to an ABI stable package. If you know some Ubuntu folks who could render an opinion, I think it would be valuable to ping them and get their thoughts. I ask because the C++11 driver currently requires 1.3.5, and I think it would be very valuable if people using the C++11 driver on the LTS could build against the system package for libbson and libmongoc.

**Comment by rcsanchez97** [comment]
The general idea was inherited from Debian's "no new upstream versions
in a stable release" policy.  The vast majority of projects are not
particularly dilligent about the scope of changes that are made in point
releases.  I understand what you are saying and I know that MongoDB is
careful, but libbson and libmongoc are only 2 packages out of thousands.

I don't personally know anyone who is involved in decisions like this in
an official capacity, but I will ask around to some folks who I think
can point me in the right direction.  Perhaps we will be able to
convince the right folks about this.

**Comment by rcsanchez97** [comment]
@ajdavis @acmorrow

It looks like there is a provision for getting new upstream point
releases into Ubuntu stable releases:

https://wiki.ubuntu.com/StableReleaseUpdates#New_upstream_microreleases

I think that there is a strong case to be made for the quality of
libbson and libmongoc and that along with the fact that they are leaf
packages (no other packages in Ubuntu depend upon them) makes them low
risk for updates.

The other option is to request a backport:

https://help.ubuntu.com/community/UbuntuBackports

That is the recommended approach when a package update is desired but
doesn't meet the stable release update criteria.

The process is really as simple as a launchpad bug requesting the update
or backport.  Would you like for me to help with either of these?

Regards,

-Roberto

**Comment by ajdavis** [comment]
Thanks Roberto. I notice one of the criteria is "the package has an
autopkgtest to run the tests in an Ubuntu environment against the actual
binary packages", which we don't have. Is that ok?

To document that we have "a reliable and credible test suite for assuring
the quality of every commit or release", I'd link them to our test server:

https://evergreen.mongodb.com/version/mongo_c_driver_e464c18ef7ea49db73753e66f3b6e994c806599b

The only failures in that test run were when we tested against an
unreleased MongoDB server version.

Yes, could you please open the launchpad bug report requesting an update?
(The first option, an "update" rather than a "backport".)

On Tue, Jun 7, 2016 at 8:28 AM, Roberto C. Sánchez <notifications@github.com

**Comment by rcsanchez97** [comment]
I'm not sure how strict the autopkgtest requirement is.  I've not used
autopkgtest before, nor it's Debian equivalent.  I've normally relied on
the package's own upstream test suite.  Sadly, the way autopkgtest is
documented is entirely focused on reproducing the setup and it never
explains what it is really about.

I think that the thoroughness of the test suites in libbson and
libmongoc should be more than enough to satisfy any testing requirement.
Plus, there are no packages depending on libmongoc or on libbson (except
for libmongoc).

I'll start the process of requesting an update.

**Comment by ajdavis** [comment]
Thanks!

**Pull request merged**
